### ISSUE TITLE
project structure and workflowhub compliance

### ISSUE THREAD

**Issue by rvosa** [o-william-white/skim2mt#13]
It might be worth considering adapting the repo structure in such a way that submissions to WorkFlowHub can proceed seamlessly. The modifications appear relatively minor (moving files around) but there would be a big benefit, to @o-william-white as well as the wider community, if this pipeline was deposited somewhere citeable. I'd be willing to help out with that.

**Comment by o-william-white** [comment]
Think this can be closed now as we have a version on workflowhub
