### ISSUE TITLE
Avoiding singularity container

### ISSUE THREAD

**Issue by o-william-white** [o-william-white/skim2mt#25]
Hi @douglowe 

Currently the pipeline uses a singularity image for the blobtools rule, which can be a problem for users on different systems. 

Blobtool installation infor here https://blobtoolkit.genomehubs.org/install/

Docker image used by singulairty here https://blobtoolkit.genomehubs.org/install/use-docker/

**Comment by douglowe** [comment]
Resolved by https://github.com/o-william-white/skim2mt/pull/26
